name: 5k Web Update


on:
  push:
    branches:
      - main

jobs:
  update-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch index.html
        run: |
          curl -o index.html https://raw.githubusercontent.com/ALD-Models/pr-tourist-map/main/index.html

      - name: Modify index.html
        run: |
          # Uncheck the junior checkbox
          sed -i 's/<input type="checkbox" id="juniorCheckbox" checked>/<input type="checkbox" id="juniorCheckbox">/g' index.html
          # Save the modified file as 5k.html
          cp index.html 5k.html

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add 5k.html
          git commit -m 'Create 5k.html with 5k markers unchecked'
          git push
