name: Update Locations

on:
  schedule:
    - cron: '0 18 * * 4' # Runs every Monday at midnight UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  fetch-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Notify Cronitor at the start of the workflow
      - name: Notify Cronitor start
        run: curl -m 10 --retry 5 -o /dev/null -s "https://cronitor.link/p/6c06f2554fc841ccb0b0928481a03ed1/fBAIJ5/run"

      - name: Fetch events.json from developer source
        run: |
          curl -sSL "https://images.parkrun.com/events.json" -o events.json
          jq '.' events.json > events1.json

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add events1.json
          git commit -m "Update events1.json file"
          git push
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Notify Cronitor based on exit status with conditions for success/failure
      - name: Notify Cronitor on exit status
        run: |
          if [ $? -eq 0 ]; then
            # Success
            curl -m 10 --retry 5 -o /dev/null -s "https://cronitor.link/p/6c06f2554fc841ccb0b0928481a03ed1/fBAIJ5/complete?msg=Success"
          else
            # Failure
            curl -m 10 --retry 5 -o /dev/null -s "https://cronitor.link/p/6c06f2554fc841ccb0b0928481a03ed1/fBAIJ5/fail?msg=Failure"
          fi
